[package]
name = "so"
version = "0.1.0"
authors = ["Sam Tay <sam.chong.tay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
clap = "2.33"
directories = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

reqwest = { version = "0.10", features = ["gzip", "json"] }
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
rayon = "1.3"

lazy_static = "1.4"
minimad = "0.6"
termimad = "0.8"

crossterm = { version = "0.17", features = ["event-stream"] }
pulldown-cmark = { version = "0.7", default-features = false }
phf = { version = "0.8", features = ["macros"] }
unicode-width = "0.1.5"

[dependencies.cursive]
version =  "0.15"
default-features = false
features = ["toml"]

[features]
default = ["cursive/termion-backend"]
windows = ["cursive/crossterm-backend"]
termion-backend = ["cursive/termion-backend"]
ncurses-backend = ["cursive/ncurses-backend"]
pancurses-backend = ["cursive/pancurses-backend"]
crossterm-backend = ["cursive/crossterm-backend"]
