[package]
name = "so"
version = "0.1.0"
authors = ["Sam Tay <sam.chong.tay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.17", features = ["event-stream"] }
clap = "2.33"
directories = "2.0"
flate2 = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
termimad = "0.8"
minimad = "0.6"
tui = { version = "0.9", default-features = false, features = ['crossterm'] }
lazy_static = "1.4"
thiserror = "1.0"
